---
- set_fact:
    serverid : "{{ hostvars[ item ]['pveid'] }}"
    servername: "{{ item }}"
    
- name: Create {{ servername }} 
  ansible.builtin.shell:
    cmd: >
        pct clone "{{ ancestor_id }}" "{{ serverid }}"
        --description "Worker node"
        --hostname "{{ servername }}" 
        --full
    creates: /etc/pve/lxc/{{ serverid }}.conf
  register: newserver

- name: Start {{ servername }} 
  ansible.builtin.shell: 
    cmd: pct start "{{ serverid }}"
    creates: "/var/lib/lxc/{{ serverid }}/apparmor"

- name: Remove {{ servername }} from known_hosts on this computer
  local_action:
    module: ansible.builtin.shell
    cmd: ssh-keygen -R "{{ servername }}"         
  when: newserver.changed
  
- name: Wait for {{ servername }} to start
  ansible.builtin.shell: lxc-wait -n "{{ serverid }}" -s RUNNING -t 120

- name: Give {{ servername }} a new SSH key
  ansible.builtin.shell: 
    cmd: lxc-attach -n "{{ serverid }}" -- /usr/bin/ssh-keygen -t ed25519 -N '' -f /root/.ssh/id_ed25519 -q 
    stdin: y
  when: newserver.changed
